// This file was automatically generated by VS extension Windows Machine Learning Code Generator VS 2017 v2,6
// from model file AirplanesClassifier.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace AirplanesClassifier.UWP
{
    
    public sealed class AirplanesClassifierInput
    {
        public ImageFeatureValue data; // BitmapPixelFormat: Bgra8, BitmapAlphaMode: Premultiplied, width: 227, height: 227
    }
    
    public sealed class AirplanesClassifierOutput
    {
        public TensorString classLabel; // shape(-1,1)
        public IList<IDictionary<string,float>> loss;
    }
    
    public sealed class AirplanesClassifierModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<AirplanesClassifierModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            AirplanesClassifierModel learningModel = new AirplanesClassifierModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<AirplanesClassifierOutput> EvaluateAsync(AirplanesClassifierInput input)
        {
            binding.Bind("data", input.data);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new AirplanesClassifierOutput();
            output.classLabel = result.Outputs["classLabel"] as TensorString;
            output.loss = result.Outputs["loss"] as IList<IDictionary<string,float>>;
            return output;
        }
    }
}

